version: '3.9'

services:
  pest-detector:
    build: .
    container_name: pest-detector-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
